<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vuelos [
  <!ELEMENT vuelos (vuelo*)>
  <!ELEMENT vuelo ((origen,destino)|(destino,origen))>
  <!ELEMENT origen (#PCDATA)>
  <!ELEMENT destino (#PCDATA)>
]>

<vuelos>
  <vuelo>
    <origen>Valencia (VLC)</origen>
    <destino>Londres Heathrow (LHR)</destino>
  </vuelo>
  <vuelo>
    <destino>Berlín Schönefeld (SFX)</destino>
    <origen>París Charles de Gaulle (CDG)</origen>
  </vuelo>
</vuelos>

<!-- se corrige el inicio del doctype añadiendo el elemento vuelos y se añade otra opción más para que los elementos puedan estar en otro orden-->